@host=http://localhost:5198
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMDBjMDllZS1jOGY1LTQ3NjktOWVhYi01N2JkNWFhNmQxM2QiLCJqdGkiOiJmMTQ1YTI2NS01Njk3LTQ4NTQtYmQ2MS03ZDMwNjgyZTlkYjgiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjk2NzU3MzMxLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.e2kit4JFElEh-BElGC6svkj8r4iOUhV5eCGExOpTsD8
@hostId=eb210a85-9fdd-4cc5-a6f9-dd275fb30000

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Delicious Menu",
    "description": "This is a yummy menu",
    "sections": [
        {
            "id": "eb210a85-9fdd-4cc5-a6f9-dd275fb30000",
            "name": "Appetizers",
            "description": "This is a yummy starter",
            "items": [
                {
                    "id": "eb210a85-9fdd-4cc5-a6f9-dd275fb30000",
                    "name": "Yummy Item",
                    "description": "This is a yummy item"
                }
            ]
        }
    ]
}