@host=http://localhost:5198
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYjIxMGE4NS05ZmRkLTRjYzUtYTZmOS1kZDI3NWZiM2FkNjciLCJqdGkiOiJkZDYxZmQ1MS1lMDFlLTRlMGItYjM2ZC02MWYyOGYzMDc5ZDAiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNjk1OTc0NTExLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.nZyjaMbfSYtrb4jyqXxxZW_T9IsjHAJBWFMaFq2Ts48
@hostId=eb210a85-9fdd-4cc5-a6f9-dd275fb30000

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "",
    "description": "This is a yummy menu",
    "sections": [
        {
            "id": "eb210a85-9fdd-4cc5-a6f9-dd275fb30000",
            "name": "Appetizers",
            "description": "This is a yummy starter",
            "items": [
                {
                    "id": "eb210a85-9fdd-4cc5-a6f9-dd275fb30000",
                    "name": "Yummy Item",
                    "description": "This is a yummy item"
                }
            ]
        }
    ]
}